### ISSUE TITLE
运行时gltf文件出不来

### ISSUE THREAD

**Issue by TomLilione** [pinky-pig/GDMap-Gltf-Direction#1]
<img width="767" alt="截屏2023-10-24 17 17 34" src="https://github.com/pinky-pig/GDMap-Gltf-Direction/assets/47802577/bc0408dd-2d55-4733-a237-0e48b473d38c">
报了个很奇怪的错误，电脑：macbook m1，
Chrome 版本 117.0.5938.132（正式版本） (arm64。
看着像google浏览器的问题

**Comment by 6owen** [comment]
我本机也是m1，没有复现这个报错🤣  
看报错截图可能是哪里requestAnimationFrame有异常阻塞了，所以可能gltf模型加载不出来吧，应该不是这里代码的问题

**Comment by TomLilione** [comment]
> 我本机也是m1，没有复现这个报错🤣 看报错截图可能是哪里requestAnimationFrame有异常阻塞了，所以可能gltf模型加载不出来吧，应该不是这里代码的问题

应该是google版本的问题，因为safari和火狐都是正常的

**Comment by 6owen** [comment]
🤣🤣
